# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: '4pgsWQKLqgOUGOOalk1KmQsqOvgwngj6'
  redis: 'b-MSzANUZeggZXIZOEn6ZWO1OzmA79mb'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'n-Ms1ZfqihLU_xtYjT2J3qqxhMof3Cbj'

  emailSecretHashPepper: 'fJgUnBM_tSDX4rx3vovICI4jOzs7xu36'
  jwtHmacSha512PrivateKey: 'Xbc_T66KNrhMyjk7TLqq34BNWc4ryf9j'
  jwtRefreshTokenHashPepper: 'ea6Wb5LdS_QYeLz4lK4yyJ3MZwgsq_DX'
  # serverSideSessionKeyHashPepper: 'DuXqrfZdnHASx1nCLgQwFbXYHHtx0-9u'

test:
  database: 'yiaclduOCFWXxMUzEOxV7xeSNto3v062'
  redis: 'he-kOG1_ozmX4sp9LBcbXCSG8tlK6gcx'

  emailSecretHashPepper: '4jlTD17BuLyOt1nJH7vnDznyU370ucpE'
  jwtHmacSha512PrivateKey: 'CY1dcQGAtgHKpflj_bMaAJNzYtUBXywM'
  jwtRefreshTokenHashPepper: 'CZs0lQc4kxdgew9T4jV1Sx-RGeU0sYZ5'
  # serverSideSessionKeyHashPepper: '8AZ6KpvB2bpL7-OQI7sPq2y9yxTyiFxS'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: 'Ce6_nT3PZq4Lzyi9ua5b5OtfST7AQFsw'
  serviceSecret: 'sAJB9bjPC2Xt98ByylCnkHD55lTJ8rNM'

  emailSecretHashPepper: 'jpjGiTztj3Y_kXbmLynX0l1dY5CuTBBH'
  jwtHmacSha512PrivateKey: 'yix37EaUbVcvjj-jB-mZVogwYxnLgnQB'
  jwtRefreshTokenHashPepper: 'bG8xYHlt-1TrUKSeF6WVgqnwIFrLuLF-'
  # serverSideSessionKeyHashPepper: 'ftpHgVaXNU7SpAunhzoJrEfkxG88NQm8'

# Passwords used in production mode.
production:
  database: '3tYckKYgBUB7h4BpZFznArI5AGAPcugf'
  serviceSecret: '3e5AfBfHUffNVqBzPMTY1mzM17UB8IO0'

  emailSecretHashPepper: '9GtXpShvFc8lmB-4EtmjZkdudeHyXaQI'
  jwtHmacSha512PrivateKey: '8-PW7PPlOWLtoD1YTZMEKnNv6BIKW94v'
  jwtRefreshTokenHashPepper: 'LtblnZkbN7bWCeH73Ap4vmeJwJ91YY_U'
  # serverSideSessionKeyHashPepper: 'Ud4XaN7RezIFl6nBJvkg9s-oOhkLDmEX'
